version: '2'
services:
    psapp-app:
        image: psapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://psapp-mysql:3306/psapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    psapp-mysql:
        extends:
            file: mysql.yml
            service: psapp-mysql
